### ISSUE TITLE
querying a non-existent word returns a 500

### ISSUE THREAD

**Issue by elmiko** [ophicleide/ophicleide-training#9]
when querying a word that does not exist in the source material, the server will return a 500 error. i would expect that it might return an empty list or something in these cases, or perhaps we should return a more standard error.

steps to reproduce:
1. create a model based off the works of jane austen (https://www.gutenberg.org/cache/epub/31100/pg31100.txt)
2. create a query for the word "bob"

results:

```
HTTP/1.0 500 INTERNAL SERVER ERROR
Content-Length: 252
Content-Type: application/problem+json
Date: Wed, 28 Sep 2016 19:06:29 GMT
Server: Werkzeug/0.11.11 Python/3.5.1

{
    "detail": "The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.",
    "status": 500,
    "title": "Internal Server Error",
    "type": "about:blank"
}
```

**Comment by elmiko** [comment]
just for completeness, here is the stack trace from the training server

```
[2016-09-28 19:06:29,807] ERROR in app: Exception on /queries [POST]
Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/connexion/decorators/validation.py", line 124, in wrapper
    response = function(*args, **kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/connexion/decorators/validation.py", line 287, in wrapper
    response = function(*args, **kwargs)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/connexion/decorators/produces.py", line 118, in wrapper
    data, status_code, headers = self.get_full_response(function(*args, **kwargs))
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/connexion/decorators/parameter.py", line 145, in wrapper
    return function(*args, **kwargs)
  File "/opt/ophicleide/controllers/default_controller.py", line 146, in create_query
    syns = w2v.findSynonyms(word, 5)
  File "/opt/ophicleide/controllers/default_controller.py", line 33, in findSynonyms
    vec = self.mat[self.indices[word_or_vec]]
KeyError: 'bob'
```
